import { db, client } from "./index";
import { user, account } from "./schema/auth-schema";
import { profile } from "./schema/profiles-schema";
import { wallet } from "./schema/wallets-schema";
import bcrypt from "bcryptjs";

const commonPassword = "Password123!";

const maleUsers = [
  {
    name: "Ahmad Fauzi",
    email: "ahmad.fauzi@example.com",
    username: "ahmadfauzi",
    displayUsername: "Ahmad Fauzi",
    birthDate: "1995-03-15",
    birthPlace: "Jakarta",
    ethnicity: "Jawa",
    height: 172,
    weight: 68,
    skinColor: "sawo matang",
    maritalStatus: "single",
    country: "Indonesia",
    city: "Jakarta",
    occupation: "Software Engineer",
    education: "S1 Teknik Informatika",
    bio: "Lulusan ITB yang bekerja sebagai software engineer di sebuah startup. Saya orang yang sederhana, suka belajar hal baru, dan sedang memperdalam ilmu agama.",
    vision: "Menjadi pribadi yang bermanfaat bagi keluarga, masyarakat, dan umat. Membangun rumah tangga yang sakinah, mawaddah, warahmah sebagai landasan untuk meraih ridha Allah.",
    mission: "1. Mendirikan rumah tangga yang islami dengan komunikasi yang baik dan saling menghormati. 2. Menjadi imam yang bertanggung jawab dan mampu membimbing keluarga menuju ketaqwaan. 3. Bekerjasama dalam kebaikan dan saling mengingatkan dalam kebenaran.",
    partnerCriteria: "Mencari wanita shalihah yang memiliki pemahaman agama yang baik, berakhlak mulia, dan memiliki semangat untuk belajar. Diharapkan dapat menjadi partner dalam membina rumah tangga yang islami.",
    partnerCity: "Jabodetabek",
    partnerOccupation: "Guru atau pekerja kantoran",
    partnerAgeMin: 22,
    partnerAgeMax: 30,
    religiousUnderstanding: "Alhamdulillah saya terus belajar ilmu agama melalui kajian offline dan online. Aktif mengikuti halaqah pekanan dan membaca buku-buku Islam.",
    manhaj: "Ahlussunnah wal Jama'ah (Salaf)",
    memorization: "Juz 30, target menghafal 5 juz dalam setahun ke depan.",
    dailyWorship: "Shalat 5 waktu berjamaah di masjid, puasa sunnah Senin Kamis, shalat tahajud, dan rutin membaca Al-Qur'an setiap hari minimal 1 halaman.",
    smokingStatus: "tidak",
    qa: [
      { question: "Apa motivasi Anda menikah?", answer: "Untuk menyempurnakan setengah agama dan membangun keluarga yang sakinah sesuai syariat." },
      { question: "Bagaimana pandangan Anda tentang peran suami istri?", answer: "Suami sebagai imam dan pemimpin, istri sebagai manager rumah tangga. Keduanya saling melengkapi dan bermusyawarah." },
      { question: "Apakah Anda bersedia tinggal di kampung halaman pasangan?", answer: "Saya terbuka asalkan masih dalam satu pulau Jawa." },
    ],
  },
  {
    name: "Rizky Pratama",
    email: "rizky.pratama@example.com",
    username: "rizkypratama",
    displayUsername: "Rizky Pratama",
    birthDate: "1997-08-22",
    birthPlace: "Bandung",
    ethnicity: "Sunda",
    height: 168,
    weight: 65,
    skinColor: "kuning langsat",
    maritalStatus: "single",
    country: "Indonesia",
    city: "Bandung",
    occupation: "Dosen",
    education: "S2 Ilmu Ekonomi",
    bio: "Dosen muda di Universitas Islam Negeri. Aktif di kegiatan dakwah kampus dan pengajian masyarakat. Hobi membaca dan travelling.",
    vision: "Menggapai ridha Allah melalui ilmu yang bermanfaat dan keluarga yang sakinah. Ingin mendidik generasi penerus yang berakhlak mulia dan berwawasan luas.",
    mission: "1. Mengamalkan ilmu yang dimiliki untuk kemaslahatan umat. 2. Membangun keluarga yang berlandaskan Al-Qur'an dan Sunnah. 3. Mendidik anak-anak menjadi generasi yang shalih dan shalihah.",
    partnerCriteria: "Wanita shalihah yang mencintai ilmu, memiliki semangat dakwah, dan bisa menjadi madrasah pertama bagi anak-anak. Lebih diutamakan yang memiliki pengalaman mengajar.",
    partnerCity: "Bandung Raya",
    partnerOccupation: "Pengajar atau pendakwah",
    partnerAgeMin: 23,
    partnerAgeMax: 30,
    religiousUnderstanding: "Belajar agama secara terstruktur melalui Ma'had Aly selama 2 tahun. Aktif mengikuti kajian para asatidz.",
    manhaj: "Ahlussunnah wal Jama'ah",
    memorization: "Juz 28, 29, 30. Sedang mentargetkan 10 juz.",
    dailyWorship: "Shalat malam, tilawah setiap hari, puasa sunnah, dan dzikir pagi petang.",
    smokingStatus: "tidak",
    qa: [
      { question: "Apa kriteria utama pasangan Anda?", answer: "Ketaqwaan dan akhlak yang baik. Ilmu bisa dipelajari bersama." },
      { question: "Bagaimana pandangan Anda tentang karir istri?", answer: "Saya mendukung selama tidak melanggar syariat dan tetap memprioritaskan keluarga." },
    ],
  },
  {
    name: "Hendra Gunawan",
    email: "hendra.gunawan@example.com",
    username: "hendragunawan",
    displayUsername: "Hendra Gunawan",
    birthDate: "1993-11-05",
    birthPlace: "Surabaya",
    ethnicity: "Madura",
    height: 175,
    weight: 72,
    skinColor: "coklat",
    maritalStatus: "single",
    country: "Indonesia",
    city: "Surabaya",
    occupation: "PNS",
    education: "S1 Administrasi Negara",
    bio: "Bekerja sebagai PNS di Pemerintahan Kota Surabaya. Sederhana, disiplin, dan bertanggung jawab. Aktif di kegiatan masjid sekitar rumah.",
    vision: "Menjadi hamba Allah yang bersyukur, keluarga yang barakah, dan bermanfaat untuk masyarakat luas.",
    mission: "1. Menjalankan amanah sebagai suami dengan sebaik-baiknya. 2. Memberikan nafkah halal dan mendidik anak dengan pendidikan Islam. 3. Berbakti kepada orang tua dan mertua.",
    partnerCriteria: "Perempuan shalihah, sopan, sederhana, dan bisa mengatur rumah tangga dengan baik. Lebih diutamakan yang bisa memasak :)",
    partnerCity: "Surabaya dan sekitarnya",
    partnerOccupation: "Tidak diutamakan",
    partnerAgeMin: 24,
    partnerAgeMax: 32,
    religiousUnderstanding: "Belajar dari kajian rutin di masjid dan membaca kitab kuning dasar bersama ustadz.",
    manhaj: "Ahlussunnah wal Jama'ah",
    memorization: "Juz 30 dan beberapa surat pilihan.",
    dailyWorship: "Shalat 5 waktu tepat waktu, shalat rawatib, puasa sunnah, dan sedekah rutin.",
    smokingStatus: "proses_berhenti",
    qa: [
      { question: "Apa kegiatan favorit Anda di waktu luang?", answer: "Olahraga ringan, membaca buku agama, dan berkebun di halaman rumah." },
      { question: "Bagaimana pandangan Anda tentang poligami?", answer: "Saya lebih memilih monogami karena khawatir tidak bisa adil." },
    ],
  },
  {
    name: "Dimas Ardiansyah",
    email: "dimas.ardiansyah@example.com",
    username: "dimasardi",
    displayUsername: "Dimas Ardiansyah",
    birthDate: "1998-06-30",
    birthPlace: "Yogyakarta",
    ethnicity: "Jawa",
    height: 170,
    weight: 63,
    skinColor: "putih",
    maritalStatus: "single",
    country: "Indonesia",
    city: "Yogyakarta",
    occupation: "UI/UX Designer",
    education: "S1 Desain Komunikasi Visual",
    bio: "Seorang desainer yang bekerja remote dari Jogja. Kreatif, santai, tapi bertanggung jawab. Sedang belajar menjadi pribadi yang lebih baik.",
    vision: "Hidup sederhana tapi bermakna. Membangun keluarga yang hangat, penuh kasih sayang, dan selalu dalam lindungan Allah.",
    mission: "1. Menjadi suami yang pengertian dan suportif. 2. Menciptakan rumah tangga yang penuh dengan nilai-nilai Islam. 3. Berbagi ilmu dan rezeki dengan sesama.",
    partnerCriteria: "Perempuan yang baik hati, pengertian, open-minded, dan memiliki keinginan untuk terus belajar agama bersama.",
    partnerCity: "Yogyakarta dan sekitarnya",
    partnerOccupation: "Kreatif atau fleksibel",
    partnerAgeMin: 22,
    partnerAgeMax: 28,
    religiousUnderstanding: "Baru mulai serius belajar agama 2 tahun terakhir. Aktif ikut kajian di Masjid Jendral Sudirman.",
    manhaj: "Masih terus belajar, cenderung ke ahlussunnah",
    memorization: "Masih tahap belajar, baru beberapa surat pendek.",
    dailyWorship: "Shalat 5 waktu, baca Al-Qur'an walau sedikit, dan berusaha istiqomah dengan amalan sunnah.",
    smokingStatus: "tidak",
    qa: [
      { question: "Apa yang Anda cari dalam seorang pasangan?", answer: "Partner hidup yang bisa saling mendukung dalam kebaikan dan menerima kekurangan masing-masing." },
    ],
  },
  {
    name: "Faisal Rahman",
    email: "faisal.rahman@example.com",
    username: "faisalrahman",
    displayUsername: "Faisal Rahman",
    birthDate: "1994-01-18",
    birthPlace: "Medan",
    ethnicity: "Batak",
    height: 178,
    weight: 75,
    skinColor: "sawo matang",
    maritalStatus: "single",
    country: "Indonesia",
    city: "Medan",
    occupation: "Pengusaha",
    education: "S1 Manajemen Bisnis",
    bio: "Pengusaha muda di bidang kuliner. Memiliki 3 cabang rumah makan di Medan. Aktif di organisasi pengusaha muda Islami.",
    vision: "Menjadi pengusaha yang sukses dunia akhirat. Membangun keluarga yang mandiri secara finansial dan kuat secara iman.",
    mission: "1. Memberikan nafkah yang berkah dan halal untuk keluarga. 2. Membangun generasi entrepreneur yang islami. 3. Berdakwah melalui bisnis dan keteladanan.",
    partnerCriteria: "Wanita shalihah yang paham manajemen rumah tangga, bisa menjadi partner berbisnis, dan tidak masalah dengan jadwal yang padat.",
    partnerCity: "Medan dan sekitarnya",
    partnerOccupation: "Pengusaha atau profesional",
    partnerAgeMin: 24,
    partnerAgeMax: 32,
    religiousUnderstanding: "Belajar melalui kajian pengusaha Islam dan mentoring pekanan bersama ustadz.",
    manhaj: "Ahlussunnah wal Jama'ah",
    memorization: "Juz 29 dan 30. Target lanjut ke juz 28.",
    dailyWorship: "Shalat subuh berjamaah di masjid, shalat dhuha, tilawah, dan infak rutin.",
    smokingStatus: "ya",
    qa: [
      { question: "Bagaimana pandangan Anda tentang peran istri bekerja?", answer: "Silakan bekerja selama tidak melanggar syariat dan tetap memprioritaskan keluarga." },
      { question: "Apa rencana Anda dalam 5 tahun ke depan?", answer: "Mengembangkan bisnis ke luar Medan dan memiliki keluarga kecil yang bahagia." },
      { question: "Bagaimana Anda menghadapi masalah?", answer: "Musyawarah dengan pasangan dan shalat istikharah." },
    ],
  },
];

const femaleUsers = [
  {
    name: "Siti Nurhaliza",
    email: "siti.nurhaliza@example.com",
    username: "sitinurhaliza",
    displayUsername: "Siti Nurhaliza",
    birthDate: "1999-05-20",
    birthPlace: "Jakarta",
    ethnicity: "Betawi",
    height: 158,
    weight: 52,
    skinColor: "kuning langsat",
    maritalStatus: "single",
    country: "Indonesia",
    city: "Jakarta",
    occupation: "Guru SD",
    education: "S1 Pendidikan",
    bio: "Guru di SDIT swasta Jakarta. Suka anak-anak dan aktif di kegiatan TPA. Berharap dapat menjadi istri dan ibu yang shalihah.",
    vision: "Menjadi wanita shalihah yang bermanfaat untuk keluarga dan masyarakat. Mendidik generasi penerus yang cinta Allah dan Rasul-Nya.",
    mission: "1. Menjadi istri yang taat dan mendukung suami dalam kebaikan. 2. Mendidik anak-anak dengan nilai-nilai Islam. 3. Terus belajar agama dan mengamalkannya.",
    partnerCriteria: "Laki-laki shalih, bertanggung jawab, memiliki pemahaman agama yang baik, dan bisa menjadi imam yang baik.",
    partnerCity: "Jabodetabek",
    partnerOccupation: "Tidak diutamakan",
    partnerAgeMin: 25,
    partnerAgeMax: 35,
    religiousUnderstanding: "Mengikuti kajian rutin Ahad pagi di masjid dekat rumah. Juga belajar online dari ustadz-ustadz ternama.",
    manhaj: "Ahlussunnah wal Jama'ah",
    memorization: "Hafal Juz 30 dan sedang mentargetkan Juz 29.",
    dailyWorship: "Shalat wajib tepat waktu, shalat dhuha, membaca Al-Qur'an setiap hari, puasa sunnah.",
    smokingStatus: "tidak",
    hijabStatus: "Ya",
    polygamyView: "Tidak Setuju",
    qa: [
      { question: "Apa kegiatan favorit Anda?", answer: "Mengajar, membaca buku parenting Islami, dan memasak." },
      { question: "Bagaimana pandangan Anda tentang ta'aruf?", answer: "Saya sangat setuju dengan proses ta'aruf karena lebih sesuai syariat dan menjaga kehormatan." },
      { question: "Apakah Anda bersedia pindah kota?", answer: "Saya bersedia asalkan masih dalam satu pulau." },
    ],
  },
  {
    name: "Aisyah Ramadhani",
    email: "aisyah.ramadhani@example.com",
    username: "aisyahramadhani",
    displayUsername: "Aisyah Ramadhani",
    birthDate: "2000-11-12",
    birthPlace: "Depok",
    ethnicity: "Sunda",
    height: 155,
    weight: 50,
    skinColor: "putih",
    maritalStatus: "single",
    country: "Indonesia",
    city: "Depok",
    occupation: "Dokter Umum",
    education: "Profesi Dokter",
    bio: "Dokter umum di RS Islam Depok. Alumni FK UI. Ingin membangun keluarga yang islami dan berkontribusi untuk umat.",
    vision: "Menjadi dokter yang diridhai Allah dan keluarga yang menjadi teladan dalam ketaqwaan.",
    mission: "1. Menyeimbangkan karir dan keluarga dengan nilai-nilai Islam. 2. Memberikan pelayanan kesehatan yang terbaik untuk umat. 3. Mendidik anak-anak menjadi generasi yang cerdas dan shalih.",
    partnerCriteria: "Laki-laki shalih, berpendidikan minimal S1, memiliki visi yang jelas, dan supportive terhadap karir selama dalam koridor syariat.",
    partnerCity: "Jabodetabek",
    partnerOccupation: "Profesional atau pengusaha",
    partnerAgeMin: 26,
    partnerAgeMax: 36,
    religiousUnderstanding: "Aktif mengikuti kajian kesehatan Islami dan mentoring pekanan.",
    manhaj: "Ahlussunnah wal Jama'ah",
    memorization: "Hafal Juz 30 dan surat-surat pilihan untuk shalat.",
    dailyWorship: "Shalat wajib, qiyamul lail, tilawah, dan rutin bersedekah.",
    smokingStatus: "tidak",
    hijabStatus: "Ya",
    polygamyView: "Bersyarat, tergantung kondisi dan kebutuhan",
    qa: [
      { question: "Bagaimana Anda membagi waktu antara karir dan ibadah?", answer: "Saya selalu memprioritaskan shalat tepat waktu dan mengatur jadwal shift dengan baik." },
      { question: "Apa harapan Anda untuk pasangan?", answer: "Bisa menjadi imam yang baik dan saling mendukung dalam kebaikan." },
    ],
  },
  {
    name: "Dewi Sartika Putri",
    email: "dewi.sartika@example.com",
    username: "dewisartika",
    displayUsername: "Dewi Sartika Putri",
    birthDate: "1998-09-03",
    birthPlace: "Bogor",
    ethnicity: "Jawa",
    height: 160,
    weight: 55,
    skinColor: "sawo matang",
    maritalStatus: "single",
    country: "Indonesia",
    city: "Bogor",
    occupation: "Content Writer",
    education: "S1 Sastra Inggris",
    bio: "Content writer di sebuah agensi digital. Suka menulis, membaca, dan belajar hal baru. Aktif di komunitas menulis Islami.",
    vision: "Menggapai ridha Allah melalui karya dan keluarga. Invisible dakwah bil qalam dan membangun generasi yang cinta ilmu.",
    mission: "1. Menjadi istri yang mendukung visi suami. 2. Mendidik anak dengan akhlak mulia. 3. Terus berkarya dan berdakwah melalui tulisan.",
    partnerCriteria: "Laki-laki yang memiliki visi dan misi hidup yang jelas, pemikiran terbuka, dan mencintai ilmu.",
    partnerCity: "Bogor, Depok, Jakarta",
    partnerOccupation: "Kreatif atau profesional",
    partnerAgeMin: 24,
    partnerAgeMax: 33,
    religiousUnderstanding: "Belajar dari buku-buku Islam dan kajian online. Aktif di komunitas Muslimah writer.",
    manhaj: "Ahlussunnah wal Jama'ah",
    memorization: "Masih belajar, baru beberapa surat dalam Juz 30.",
    dailyWorship: "Shalat wajib, tilawah, puasa sunnah, dan istiqomah dengan wirid harian.",
    smokingStatus: "tidak",
    hijabStatus: "Kadang-kadang, masih berusaha istiqomah",
    polygamyView: "Tidak Setuju",
    qa: [
      { question: "Apa buku favorit Anda?", answer: "La Tahzan, Riyadhus Shalihin, dan buku-buku karya Salim A. Fillah." },
      { question: "Apa pendapat Anda tentang rumah tangga?", answer: "Rumah tangga adalah ladang ibadah terbesar setelah iman." },
    ],
  },
  {
    name: "Nadia Rahmawati",
    email: "nadia.rahmawati@example.com",
    username: "nadiarahma",
    displayUsername: "Nadia Rahmawati",
    birthDate: "1996-04-27",
    birthPlace: "Palembang",
    ethnicity: "Palembang",
    height: 162,
    weight: 57,
    skinColor: "kuning langsat",
    maritalStatus: "single",
    country: "Indonesia",
    city: "Palembang",
    occupation: "Arsitek",
    education: "S1 Arsitektur",
    bio: "Arsitek di sebuah firma ternama di Palembang. Desain rumah Islami adalah spesialisasi saya. Ingin membangun rumah tangga yang seindah desain terbaik.",
    vision: "Membangun peradaban Islam melalui arsitektur yang berkah dan keluarga yang sakinah.",
    mission: "1. Menjadi istri yang shalihah dan profesional. 2. Mendidik anak dengan nilai-nilai keislaman dan kreativitas. 3. Berdakwah melalui desain arsitektur Islami.",
    partnerCriteria: "Laki-laki shalih, visioner, bertanggung jawab, dan menghargai profesi pasangan.",
    partnerCity: "Palembang dan sekitarnya",
    partnerOccupation: "Profesional atau pengusaha",
    partnerAgeMin: 27,
    partnerAgeMax: 36,
    religiousUnderstanding: "Mengikuti halaqah Muslimah pekanan dan kajian arsitektur Islam.",
    manhaj: "Ahlussunnah wal Jama'ah",
    memorization: "Juz 30 dan target menambah hafalan.",
    dailyWorship: "Shalat wajib, shalat rawatib, tilawah harian, dan puasa sunnah.",
    smokingStatus: "tidak",
    hijabStatus: "Ya",
    polygamyView: "Bersyarat, asalkan ada alasan syar'i dan adil",
    qa: [
      { question: "Apa impian terbesar Anda?", answer: "Memiliki keluarga kecil yang bahagia dan bisa mendesain masjid di berbagai daerah." },
    ],
  },
  {
    name: "Maya Hasanah",
    email: "maya.hasanah@example.com",
    username: "mayahasanah",
    displayUsername: "Maya Hasanah",
    birthDate: "1997-07-14",
    birthPlace: "Semarang",
    ethnicity: "Jawa",
    height: 156,
    weight: 48,
    skinColor: "putih",
    maritalStatus: "widowed",
    country: "Indonesia",
    city: "Semarang",
    occupation: "Akuntan",
    education: "S1 Akuntansi",
    bio: "Akuntan di perusahaan swasta. Seorang janda tanpa anak yang ingin membuka lembaran baru. Aktif di kajian Muslimah dan pengajian bulanan.",
    vision: "Menjadi wanita yang kuat imannya, ikhlas menerima takdir, dan siap membangun keluarga sakinah di sisa usia.",
    mission: "1. Menjadi istri yang terbaik untuk suami. 2. Membangun rumah tangga yang penuh keberkahan. 3. Terus memperbaiki diri dan mendekatkan diri kepada Allah.",
    partnerCriteria: "Laki-laki shalih yang bertanggung jawab, bisa menerima masa lalu, dan memiliki komitmen untuk membina rumah tangga Islami.",
    partnerCity: "Semarang dan sekitarnya",
    partnerOccupation: "Tidak diutamakan",
    partnerAgeMin: 28,
    partnerAgeMax: 40,
    religiousUnderstanding: "Belajar dari kajian Muslimah dan mentoring pribadi dengan ustadzah.",
    manhaj: "Ahlussunnah wal Jama'ah",
    memorization: "Juz 30. Target menghafal surat-surat pilihan untuk ketenangan hati.",
    dailyWorship: "Shalat 5 waktu, tahajud, istighfar pagi petang, dan puasa senin kamis.",
    smokingStatus: "tidak",
    hijabStatus: "Ya",
    polygamyView: "Setuju, asalkan suami mampu berlaku adil",
    qa: [
      { question: "Apa yang Anda pelajari dari pengalaman pernikahan sebelumnya?", answer: "Saya belajar untuk lebih bersabar, lebih memahami takdir, dan lebih mempersiapkan diri secara mental dan spiritual." },
      { question: "Apa harapan Anda untuk pernikahan kali ini?", answer: "Semoga Allah memberikan ketenangan hati dan pasangan yang saling menerima." },
      { question: "Apakah Anda bersedia tinggal di kota pasangan?", answer: "Saya bersedia, asalkan dengan musyawarah bersama." },
    ],
  },
];

async function hashPassword(password: string): Promise<string> {
  return await bcrypt.hash(password, 10);
}

async function seed() {
  console.log("🌱 Seeding database...\n");

  console.log("  Clearing existing data...");
  await db.delete(profile);
  await db.delete(account);
  await db.delete(wallet);
  await db.delete(user);
  console.log("  Done clearing.\n");

  const hashedPassword = await hashPassword(commonPassword);

  const allUsers = [
    ...maleUsers.map((u) => ({ ...u, gender: "male" as const })),
    ...femaleUsers.map((u) => ({ ...u, gender: "female" as const })),
  ];

  for (const u of allUsers) {
    const userId = crypto.randomUUID();
    const profileId = crypto.randomUUID();

    console.log(`  Creating user: ${u.name} (@${u.username})`);

    await db.insert(user).values({
      id: userId,
      name: u.name,
      email: u.email,
      emailVerified: true,
      username: u.username,
      displayUsername: u.displayUsername,
      gender: u.gender,
      role: "candidate",
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    await db.insert(account).values({
      id: crypto.randomUUID(),
      accountId: u.email,
      providerId: "credential",
      userId,
      password: hashedPassword,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    const photoUrl = `https://api.dicebear.com/9.x/avataaars/png?seed=${u.username}&size=400`;

    await db.insert(profile).values({
      id: profileId,
      userId,
      photoUrl,
      photoBlurredUrl: photoUrl,
      gender: u.gender,
      birthDate: u.birthDate,
      birthPlace: u.birthPlace,
      ethnicity: u.ethnicity,
      height: u.height,
      weight: u.weight,
      skinColor: u.skinColor,
      maritalStatus: u.maritalStatus,
      country: u.country,
      city: u.city,
      occupation: u.occupation,
      education: u.education,
      bio: u.bio,
      vision: u.vision,
      mission: u.mission,
      partnerCriteria: u.partnerCriteria,
      partnerCity: u.partnerCity,
      partnerOccupation: u.partnerOccupation,
      partnerAgeMin: u.partnerAgeMin,
      partnerAgeMax: u.partnerAgeMax,
      religiousUnderstanding: u.religiousUnderstanding,
      manhaj: u.manhaj,
      memorization: u.memorization,
      dailyWorship: u.dailyWorship,
      ...(u.gender === "female" ? { hijabStatus: u.hijabStatus ?? null, polygamyView: u.polygamyView ?? null } : {}),
      smokingStatus: u.smokingStatus ?? null,
      qa: u.qa ?? null,
      cvStatus: "approved",
      published: true,
      photoBlurred: true,
      onboardingCompleted: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    await db.insert(wallet).values({
      id: crypto.randomUUID(),
      userId,
      balance: 10,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  const adminId = crypto.randomUUID();
  console.log("  Creating admin user: Admin Pethuk (@adminpethuk)");

  const adminHashed = await hashPassword(commonPassword);

  await db.insert(user).values({
    id: adminId,
    name: "Admin Pethuk",
    email: "admin@pethukjodoh.com",
    emailVerified: true,
    username: "adminpethuk",
    displayUsername: "Admin Pethuk",
    gender: "male",
    role: "admin",
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  await db.insert(account).values({
    id: crypto.randomUUID(),
    accountId: "admin@pethukjodoh.com",
    providerId: "credential",
    userId: adminId,
    password: adminHashed,
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  console.log(`\n✅ Seeded ${allUsers.length + 1} users successfully!`);
  console.log(`   Password untuk semua user: ${commonPassword}`);
  console.log(`   Login dengan email masing-masing.\n`);
}

seed()
  .catch((err) => {
    console.error("❌ Seed failed:", err);
    process.exit(1);
  })
  .finally(() => {
    client.end();
  });
