import { profile, user } from "@/db/schema";

export const candidateFullSelect = {
  id: profile.id,
  userId: profile.userId,
  gender: profile.gender,
  birthDate: profile.birthDate,
  birthPlace: profile.birthPlace,
  ethnicity: profile.ethnicity,
  city: profile.city,
  occupation: profile.occupation,
  education: profile.education,
  maritalStatus: profile.maritalStatus,
  skinColor: profile.skinColor,
  height: profile.height,
  weight: profile.weight,
  childCount: profile.childCount,
  hairColor: profile.hairColor,
  hairType: profile.hairType,
  hijabStatus: profile.hijabStatus,
  faceAppearance: profile.faceAppearance,
  otherPhysicalTraits: profile.otherPhysicalTraits,
  marriageTarget: profile.marriageTarget,
  polygamyView: profile.polygamyView,
  parentsInvolvement: profile.parentsInvolvement,
  smokingStatus: profile.smokingStatus,
  personalityTraits: profile.personalityTraits,
  interests: profile.interests,
  bio: profile.bio,
  vision: profile.vision,
  mission: profile.mission,
  qa: profile.qa,
  partnerCriteria: profile.partnerCriteria,
  partnerCity: profile.partnerCity,
  partnerOccupation: profile.partnerOccupation,
  partnerAgeMin: profile.partnerAgeMin,
  partnerAgeMax: profile.partnerAgeMax,
  religiousUnderstanding: profile.religiousUnderstanding,
  manhaj: profile.manhaj,
  memorization: profile.memorization,
  dailyWorship: profile.dailyWorship,
  photoUrl: profile.photoUrl,
  photoBlurredUrl: profile.photoBlurredUrl,
  photoBlurred: profile.photoBlurred,
  ktpUrl: profile.ktpUrl,
  username: user.username,
  name: user.name,
  createdAt: profile.createdAt,
};

export const candidateListSelect = {
  id: profile.id,
  userId: profile.userId,
  gender: profile.gender,
  birthDate: profile.birthDate,
  birthPlace: profile.birthPlace,
  city: profile.city,
  occupation: profile.occupation,
  education: profile.education,
  maritalStatus: profile.maritalStatus,
  skinColor: profile.skinColor,
  height: profile.height,
  weight: profile.weight,
  bio: profile.bio,
  vision: profile.vision,
  mission: profile.mission,
  photoBlurredUrl: profile.photoBlurredUrl,
  ethnicity: profile.ethnicity,
  username: user.username,
  religiousUnderstanding: profile.religiousUnderstanding,
  manhaj: profile.manhaj,
  memorization: profile.memorization,
  dailyWorship: profile.dailyWorship,
  createdAt: profile.createdAt,
  name: user.name,
} as const;
